### ISSUE TITLE
Playing the song

### ISSUE THREAD

**Issue by mohammad-moa** [immdipu/Beatstreet#1]
When I click on a song that is displayed in the sidebar and I try to play it, there is a problem (the problem is the time of the whole song, which is NaN, and its execution)

**Comment by immdipu** [comment]
Thanks for reporting the issue. I couldn't reproduce it, but I think it might be due to slow internet connectivity which might have resulted in the song's information not being fully loaded. If the problem persists, please share a screenshot or any additional information that can help me understand and resolve the issue. Thanks!

**Comment by immdipu** [comment]
Thanks for reporting the issue. I couldn't reproduce it, but I think it might be due to slow internet connectivity which might have resulted in the song's information not being fully loaded. If the problem persists, please share a screenshot or any additional information that can help me understand and resolve the issue. Thanks!

**Comment by mohammad-moa** [comment]
Thank you, according to the picture below, I have determined that the song has been played and after clicking on the play button, the time display of the entire song appears in the form of NaN:NaN, which I think can be from the side bar component of the song
![Screenshot 2023-04-09 133211](https://user-images.githubusercontent.com/85023397/230763806-f7b49fb4-cad0-4b7f-9021-1c914b9ed74e.png)
